wp-ee-db:
  image: lamtrantuan/docker-easyengine-stack:db
  env_file: .env
  volumes:
    - /var/lib/mysql:/var/lib/mysql
  ports:
    - 3306:3306
wp-ee-web:
  image: lamtrantuan/docker-easyengine-stack:web
  env_file: .env
  volumes:
    - /var/www:/var/www
    - /etc/nginx:/etc/nginx
    - /var/lib/ee:/var/lib/ee
    - /etc/ee:/etc/ee
  links:
    - wp-ee-db:mysql
  ports:
    - 80:80
    - 443:443
    - 22222:22222
